version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:4.0.0-rc-3-20211010
    ports:
      - 4444:4444
      - 5900:5900

  app:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true
